version: "3.9"

services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: traffic_postgres
    restart: always
    environment:
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_pass
      POSTGRES_DB: traffic_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traffic_user -d traffic_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: traffiq_backend
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgresql://traffic_user:traffic_pass@postgres:5432/traffic_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: traffiq_frontend
    restart: always
    environment:
      API_URL: http://backend:8000/rag/query
    ports:
      - "7860:7860"
    depends_on:
      - backend
