version: "3.9"

services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: traffic_postgres
    restart: always
    environment:
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_pass
      POSTGRES_DB: traffic_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  